import Store from 'electron-store'
import { synthesisRepo } from '../db/repositories/synthesis.repo'
import { transcriptsRepo } from '../db/repositories/transcripts.repo'
import { eventsRepo } from '../db/repositories/events.repo'
import type { ConfluencePage, Synthesis } from '../../shared/types'

const store = new Store<{
  confluenceBaseUrl: string
  confluenceEmail: string
  confluenceApiToken: string
}>()

function getAuthHeader(): string {
  const email = store.get('confluenceEmail', '') as string
  const token = store.get('confluenceApiToken', '') as string
  return 'Basic ' + Buffer.from(`${email}:${token}`).toString('base64')
}

/** Normalize whatever the user typed into a clean https://hostname origin */
function getBaseUrl(): string {
  let rawUrl = (store.get('confluenceBaseUrl', '') as string).trim()
  if (!rawUrl) throw new Error('Confluence base URL not configured. Set it in Settings.')
  if (!/^https?:\/\//i.test(rawUrl)) rawUrl = 'https://' + rawUrl
  return new URL(rawUrl).origin
}

function synthesisToConfluenceHtml(synthesis: Synthesis, eventTitle: string, eventMeta: string): string {
  const insights = synthesis.keyDecisions.map((i) => `<li>${i}</li>`).join('')
  const steps = synthesis.nextSteps.map((s) => `<li>${s}</li>`).join('')
  const notesSection = synthesis.notes?.trim()
    ? `<h3>Notes</h3><p>${synthesis.notes.trim().replace(/\n/g, '<br/>')}</p>`
    : ''

  return `
<h2>Meeting: ${eventTitle}</h2>
<p><em>Generated by Recall on ${new Date().toLocaleDateString()}</em></p>
${eventMeta}
<h3>Summary</h3>
<p>${synthesis.meetingSummary ?? ''}</p>

<h3>Attendees</h3>
<p>${synthesis.attendeesSummary ?? ''}</p>

<h3>Discussion</h3>
<p>${synthesis.discussion ?? ''}</p>

<h3>Key Decisions</h3>
<ul>${insights}</ul>

<h3>Next Steps</h3>
<ul>${steps}</ul>
${notesSection}
`
}

async function resolveSpaceId(baseUrl: string, spaceKey: string): Promise<string> {
  // If already numeric, use as-is
  if (/^\d+$/.test(spaceKey)) return spaceKey

  const response = await fetch(
    `${baseUrl}/wiki/api/v2/spaces?keys=${encodeURIComponent(spaceKey)}&limit=1`,
    {
      headers: {
        Authorization: getAuthHeader(),
        Accept: 'application/json',
      },
    }
  )

  if (!response.ok) {
    const text = await response.text()
    throw new Error(`Failed to look up Confluence space "${spaceKey}": ${response.status} ${text}`)
  }

  const data = (await response.json()) as { results?: { id: string }[] }
  const spaceId = data.results?.[0]?.id
  if (!spaceId) {
    throw new Error(
      `Confluence space "${spaceKey}" not found. Check the space key in your label settings.`
    )
  }
  return spaceId
}

export async function getSpacePages(spaceKey: string): Promise<ConfluencePage[]> {
  const baseUrl = getBaseUrl()
  const allPages: ConfluencePage[] = []
  const PAGE_SIZE = 250
  let start = 0

  while (true) {
    const response = await fetch(
      `${baseUrl}/wiki/rest/api/content?type=page&spaceKey=${encodeURIComponent(spaceKey)}&limit=${PAGE_SIZE}&start=${start}&orderby=title`,
      {
        headers: {
          Authorization: getAuthHeader(),
          Accept: 'application/json',
        },
      }
    )

    if (!response.ok) {
      const text = await response.text()
      throw new Error(`Failed to fetch Confluence pages: ${response.status} ${text}`)
    }

    const data = (await response.json()) as { results?: Array<{ id: string; title: string }> }
    const results = data.results ?? []
    allPages.push(...results.map((p) => ({ id: p.id, title: p.title })))

    // Stop if we got fewer results than the page size (last page) or hit safety cap
    if (results.length < PAGE_SIZE || allPages.length >= 2000) break
    start += PAGE_SIZE
  }

  return allPages
}

/** Strip HTML tags and collapse whitespace to plain text */
function htmlToPlainText(html: string): string {
  return html
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/\s+/g, ' ')
    .trim()
}

/**
 * Fetch page titles + body excerpts from the given Confluence space keys.
 * Used to build context for the on-device chat assistant.
 * Fetches up to 5 most-recently-modified pages per space, capped at 300 chars each.
 */
export async function fetchSpaceSummariesForChat(spaceKeys: string[]): Promise<string> {
  if (spaceKeys.length === 0) return ''
  const baseUrl = getBaseUrl()
  const sections: string[] = []

  for (const spaceKey of spaceKeys.slice(0, 3)) {
    const response = await fetch(
      `${baseUrl}/wiki/rest/api/content?type=page&spaceKey=${encodeURIComponent(spaceKey)}&limit=5&orderby=modified&expand=body.view`,
      { headers: { Authorization: getAuthHeader(), Accept: 'application/json' } }
    )
    if (!response.ok) continue

    const data = (await response.json()) as {
      results?: Array<{ title: string; body?: { view?: { value?: string } } }>
    }

    for (const page of data.results ?? []) {
      const bodyHtml = page.body?.view?.value ?? ''
      const excerpt = htmlToPlainText(bodyHtml).slice(0, 300)
      sections.push(`**${page.title}**${excerpt ? `\n${excerpt}…` : ''}`)
    }
  }

  return sections.join('\n\n')
}

export async function pushSynthesis(synthesisId: string): Promise<{ url: string }> {
  const baseUrl = getBaseUrl()

  const synthesis = synthesisRepo.getById(synthesisId)
  if (!synthesis) throw new Error(`Synthesis not found: ${synthesisId}`)

  const transcript = transcriptsRepo.getById(synthesis.transcriptId, true)
  if (!transcript) throw new Error('Transcript not found')

  const eventTitle = transcript.event?.title ?? 'Untitled Meeting'

  // Build event metadata block for Confluence HTML
  let eventMeta = ''
  if (transcript.event) {
    const ev = transcript.event
    const start = new Date(ev.startTime).toLocaleString()
    const attendeeNames = ev.attendees.map((a) => a.name || a.email).join(', ')
    eventMeta = `<p><strong>Date:</strong> ${start}</p>`
    if (attendeeNames) eventMeta += `<p><strong>Attendees:</strong> ${attendeeNames}</p>`
    if (ev.description) eventMeta += `<p><strong>Description:</strong> ${ev.description}</p>`
  }

  // Always fetch labels fresh from DB — the event snapshot on the transcript may be stale
  const labels = transcript.event ? eventsRepo.getLabelsForEvent(transcript.event.id) : []
  const labelWithDest = labels.find((l) => l.confluenceSpaceKey)

  console.log('[confluence] event:', transcript.event?.id, 'labels:', JSON.stringify(labels))

  if (labels.length === 0) {
    throw new Error(
      `This meeting has no labels assigned (eventId=${transcript.event?.id ?? 'null'}). ` +
      'Assign a label with a Confluence Space Key to the event on the Home screen, then try again.'
    )
  }

  if (!labelWithDest) {
    const labelNames = labels.map((l) => `"${l.name}"`).join(', ')
    throw new Error(
      `The label(s) on this meeting (${labelNames}) don't have a Confluence Space Key configured. ` +
      'Edit the label in the Project Labels page to add a Space Key.'
    )
  }

  // Resolve space key → numeric space ID required by v2 API
  const spaceId = await resolveSpaceId(baseUrl, labelWithDest.confluenceSpaceKey!)

  const body: Record<string, unknown> = {
    title: `${eventTitle} — ${new Date().toLocaleDateString()}`,
    spaceId,
    body: {
      representation: 'storage',
      value: synthesisToConfluenceHtml(synthesis, eventTitle, eventMeta),
    },
  }

  if (labelWithDest.confluencePageId && /^\d+$/.test(labelWithDest.confluencePageId)) {
    body['parentId'] = labelWithDest.confluencePageId
  }

  const response = await fetch(`${baseUrl}/wiki/api/v2/pages`, {
    method: 'POST',
    headers: {
      Authorization: getAuthHeader(),
      'Content-Type': 'application/json',
      Accept: 'application/json',
    },
    body: JSON.stringify(body),
  })

  if (!response.ok) {
    const text = await response.text()
    throw new Error(`Confluence API error ${response.status}: ${text}`)
  }

  const data = (await response.json()) as { _links?: { webui?: string }; id?: string }
  const pageUrl = data._links?.webui
    ? `${baseUrl}${data._links.webui}`
    : `${baseUrl}/wiki/spaces/${labelWithDest.confluenceSpaceKey}`

  synthesisRepo.markPushed(synthesisId, pageUrl)

  return { url: pageUrl }
}
