import Store from 'electron-store'
import { synthesisRepo } from '../db/repositories/synthesis.repo'
import { transcriptsRepo } from '../db/repositories/transcripts.repo'
import { eventsRepo } from '../db/repositories/events.repo'
import type { ConfluencePage, Synthesis } from '../../shared/types'

const store = new Store<{
  confluenceBaseUrl: string
  confluenceEmail: string
  confluenceApiToken: string
}>()

function getAuthHeader(): string {
  const email = store.get('confluenceEmail', '') as string
  const token = store.get('confluenceApiToken', '') as string
  return 'Basic ' + Buffer.from(`${email}:${token}`).toString('base64')
}

/** Normalize whatever the user typed into a clean https://hostname origin */
function getBaseUrl(): string {
  let rawUrl = (store.get('confluenceBaseUrl', '') as string).trim()
  if (!rawUrl) throw new Error('Confluence base URL not configured. Set it in Settings.')
  if (!/^https?:\/\//i.test(rawUrl)) rawUrl = 'https://' + rawUrl
  return new URL(rawUrl).origin
}

function synthesisToConfluenceHtml(synthesis: Synthesis, eventTitle: string, eventMeta: string): string {
  const insights = synthesis.keyDecisions.map((i) => `<li>${i}</li>`).join('')
  const steps = synthesis.nextSteps.map((s) => `<li>${s}</li>`).join('')
  const notesSection = synthesis.notes?.trim()
    ? `<h3>Notes</h3><p>${synthesis.notes.trim().replace(/\n/g, '<br/>')}</p>`
    : ''

  return `
<h2>Meeting: ${eventTitle}</h2>
<p><em>Generated by Recall on ${new Date().toLocaleDateString()}</em></p>
${eventMeta}
<h3>Summary</h3>
<p>${synthesis.meetingSummary ?? ''}</p>

<h3>Attendees</h3>
<p>${synthesis.attendeesSummary ?? ''}</p>

<h3>Discussion</h3>
<p>${synthesis.discussion ?? ''}</p>

<h3>Key Decisions</h3>
<ul>${insights}</ul>

<h3>Next Steps</h3>
<ul>${steps}</ul>
${notesSection}
`
}

async function resolveSpaceId(baseUrl: string, spaceKey: string): Promise<string> {
  // If already numeric, use as-is
  if (/^\d+$/.test(spaceKey)) return spaceKey

  const response = await fetch(
    `${baseUrl}/wiki/api/v2/spaces?keys=${encodeURIComponent(spaceKey)}&limit=1`,
    {
      headers: {
        Authorization: getAuthHeader(),
        Accept: 'application/json',
      },
    }
  )

  if (!response.ok) {
    const text = await response.text()
    throw new Error(`Failed to look up Confluence space "${spaceKey}": ${response.status} ${text}`)
  }

  const data = (await response.json()) as { results?: { id: string }[] }
  const spaceId = data.results?.[0]?.id
  if (!spaceId) {
    throw new Error(
      `Confluence space "${spaceKey}" not found. Check the space key in your label settings.`
    )
  }
  return spaceId
}

export async function getSpacePages(spaceKey: string): Promise<ConfluencePage[]> {
  const baseUrl = getBaseUrl()

  // Step 1: resolve space key → numeric space ID (v2 API requires numeric ID)
  const spaceId = await resolveSpaceId(baseUrl, spaceKey)

  // Step 2: fetch ALL pages via v2 API — returns parentId + parentType correctly,
  // including pages whose immediate parent is a Confluence Cloud folder.
  type V2Page = {
    id: string
    title: string
    parentId: string | null
    parentType: string | null
  }

  const v2Pages: V2Page[] = []
  let cursor: string | undefined

  while (true) {
    const url = new URL(`${baseUrl}/wiki/api/v2/pages`)
    url.searchParams.set('space-id', spaceId)
    url.searchParams.set('limit', '250')
    if (cursor) url.searchParams.set('cursor', cursor)

    const response = await fetch(url.toString(), {
      headers: { Authorization: getAuthHeader(), Accept: 'application/json' },
    })

    if (!response.ok) {
      const text = await response.text()
      throw new Error(`Failed to fetch Confluence pages: ${response.status} ${text}`)
    }

    const data = (await response.json()) as {
      results?: V2Page[]
      _links?: { next?: string }
    }

    const results = data.results ?? []
    v2Pages.push(...results)

    // v2 pagination uses cursor-based links
    const nextLink = data._links?.next
    if (!nextLink || results.length === 0 || v2Pages.length >= 2000) break

    // Extract cursor from the next link query string
    const nextUrl = new URL(`${baseUrl}${nextLink}`)
    cursor = nextUrl.searchParams.get('cursor') ?? undefined
    if (!cursor) break
  }

  // Step 3: collect unique folder IDs (parentType === 'folder')
  const folderIds = new Set<string>()
  for (const page of v2Pages) {
    if (page.parentId && page.parentType === 'folder') {
      folderIds.add(page.parentId)
    }
  }

  // Step 4: fetch folder details individually via v1 API with expand=ancestors
  // so we get each folder's title and its own ancestor chain.
  type V1Content = {
    id: string
    title: string
    ancestors?: Array<{ id: string; title: string; type?: string }>
  }

  const folderDetails = new Map<string, V1Content>()
  await Promise.all(
    Array.from(folderIds).map(async (folderId) => {
      try {
        const response = await fetch(
          `${baseUrl}/wiki/rest/api/content/${encodeURIComponent(folderId)}?expand=ancestors`,
          { headers: { Authorization: getAuthHeader(), Accept: 'application/json' } }
        )
        if (!response.ok) return
        const data = (await response.json()) as V1Content
        folderDetails.set(folderId, data)
        // Also discover ancestor folder IDs we haven't seen yet
        for (const anc of data.ancestors ?? []) {
          if (!folderIds.has(anc.id)) {
            folderIds.add(anc.id)
          }
        }
      } catch {
        // ignore individual folder fetch failures
      }
    })
  )

  // Fetch any newly discovered ancestor folders (one extra pass is enough in practice)
  const secondPassIds = Array.from(folderIds).filter((id) => !folderDetails.has(id))
  await Promise.all(
    secondPassIds.map(async (folderId) => {
      try {
        const response = await fetch(
          `${baseUrl}/wiki/rest/api/content/${encodeURIComponent(folderId)}?expand=ancestors`,
          { headers: { Authorization: getAuthHeader(), Accept: 'application/json' } }
        )
        if (!response.ok) return
        const data = (await response.json()) as V1Content
        folderDetails.set(folderId, data)
      } catch {
        // ignore
      }
    })
  )

  // Step 5: build a complete node map
  const nodesById = new Map<string, ConfluencePage>()

  // Add all folder nodes first, synthesising ancestor chain from v1 ancestors array
  for (const [, folder] of folderDetails) {
    const ancestors = folder.ancestors ?? []

    // Synthesise any ancestor nodes not already present
    for (let i = 0; i < ancestors.length; i++) {
      const anc = ancestors[i]
      if (!nodesById.has(anc.id)) {
        nodesById.set(anc.id, {
          id: anc.id,
          title: anc.title,
          parentId: i > 0 ? ancestors[i - 1].id : null,
          path: ancestors.slice(0, i + 1).map((a) => a.title).join(' / '),
          isFolder: true,
        })
      }
    }

    const parentId = ancestors.length > 0 ? ancestors[ancestors.length - 1].id : null
    const path = [...ancestors.map((a) => a.title), folder.title].join(' / ')
    nodesById.set(folder.id, { id: folder.id, title: folder.title, parentId, path, isFolder: true })
  }

  // Add all page nodes
  for (const page of v2Pages) {
    nodesById.set(page.id, {
      id: page.id,
      title: page.title,
      parentId: page.parentId,
      path: '', // computed in next pass
    })
  }

  // Step 6: compute paths for all nodes via parent traversal
  function getPath(id: string, visited = new Set<string>()): string {
    if (visited.has(id)) return '' // cycle guard
    visited.add(id)
    const node = nodesById.get(id)
    if (!node) return ''
    if (!node.parentId || !nodesById.has(node.parentId)) return node.title
    return getPath(node.parentId, visited) + ' / ' + node.title
  }

  for (const node of nodesById.values()) {
    node.path = getPath(node.id)
  }

  return Array.from(nodesById.values())
}

/** Strip HTML tags and collapse whitespace to plain text */
function htmlToPlainText(html: string): string {
  return html
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/\s+/g, ' ')
    .trim()
}

/**
 * Fetch page titles + body excerpts from the given Confluence space keys.
 * Used to build context for the on-device chat assistant.
 * Fetches up to 5 most-recently-modified pages per space, capped at 300 chars each.
 */
export async function fetchSpaceSummariesForChat(spaceKeys: string[]): Promise<string> {
  if (spaceKeys.length === 0) return ''
  const baseUrl = getBaseUrl()
  const sections: string[] = []

  for (const spaceKey of spaceKeys.slice(0, 3)) {
    const response = await fetch(
      `${baseUrl}/wiki/rest/api/content?type=page&spaceKey=${encodeURIComponent(spaceKey)}&limit=5&orderby=modified&expand=body.view`,
      { headers: { Authorization: getAuthHeader(), Accept: 'application/json' } }
    )
    if (!response.ok) continue

    const data = (await response.json()) as {
      results?: Array<{ title: string; body?: { view?: { value?: string } } }>
    }

    for (const page of data.results ?? []) {
      const bodyHtml = page.body?.view?.value ?? ''
      const excerpt = htmlToPlainText(bodyHtml).slice(0, 300)
      sections.push(`**${page.title}**${excerpt ? `\n${excerpt}…` : ''}`)
    }
  }

  return sections.join('\n\n')
}

export async function pushSynthesis(synthesisId: string): Promise<{ url: string }> {
  const baseUrl = getBaseUrl()

  const synthesis = synthesisRepo.getById(synthesisId)
  if (!synthesis) throw new Error(`Synthesis not found: ${synthesisId}`)

  const transcript = transcriptsRepo.getById(synthesis.transcriptId, true)
  if (!transcript) throw new Error('Transcript not found')

  const eventTitle = transcript.event?.title ?? 'Untitled Meeting'

  // Build event metadata block for Confluence HTML
  let eventMeta = ''
  if (transcript.event) {
    const ev = transcript.event
    const start = new Date(ev.startTime).toLocaleString()
    const attendeeNames = ev.attendees.map((a) => a.name || a.email).join(', ')
    eventMeta = `<p><strong>Date:</strong> ${start}</p>`
    if (attendeeNames) eventMeta += `<p><strong>Attendees:</strong> ${attendeeNames}</p>`
    if (ev.description) eventMeta += `<p><strong>Description:</strong> ${ev.description}</p>`
  }

  // Always fetch labels fresh from DB — the event snapshot on the transcript may be stale
  const labels = transcript.event ? eventsRepo.getLabelsForEvent(transcript.event.id) : []
  const labelWithDest = labels.find((l) => l.confluenceSpaceKey)

  console.log('[confluence] event:', transcript.event?.id, 'labels:', JSON.stringify(labels))

  if (labels.length === 0) {
    throw new Error(
      `This meeting has no labels assigned (eventId=${transcript.event?.id ?? 'null'}). ` +
      'Assign a label with a Confluence Space Key to the event on the Home screen, then try again.'
    )
  }

  if (!labelWithDest) {
    const labelNames = labels.map((l) => `"${l.name}"`).join(', ')
    throw new Error(
      `The label(s) on this meeting (${labelNames}) don't have a Confluence Space Key configured. ` +
      'Edit the label in the Project Labels page to add a Space Key.'
    )
  }

  // Resolve space key → numeric space ID required by v2 API
  const spaceId = await resolveSpaceId(baseUrl, labelWithDest.confluenceSpaceKey!)

  const body: Record<string, unknown> = {
    title: `${eventTitle} — ${new Date().toLocaleDateString()}`,
    spaceId,
    body: {
      representation: 'storage',
      value: synthesisToConfluenceHtml(synthesis, eventTitle, eventMeta),
    },
  }

  if (labelWithDest.confluencePageId && /^\d+$/.test(labelWithDest.confluencePageId)) {
    body['parentId'] = labelWithDest.confluencePageId
  }

  const response = await fetch(`${baseUrl}/wiki/api/v2/pages`, {
    method: 'POST',
    headers: {
      Authorization: getAuthHeader(),
      'Content-Type': 'application/json',
      Accept: 'application/json',
    },
    body: JSON.stringify(body),
  })

  if (!response.ok) {
    const text = await response.text()
    throw new Error(`Confluence API error ${response.status}: ${text}`)
  }

  const data = (await response.json()) as { _links?: { webui?: string }; id?: string }
  const pageUrl = data._links?.webui
    ? `${baseUrl}${data._links.webui}`
    : `${baseUrl}/wiki/spaces/${labelWithDest.confluenceSpaceKey}`

  synthesisRepo.markPushed(synthesisId, pageUrl)

  return { url: pageUrl }
}
